const COLORS = {
  Red:{hex:'#dc2626',filter:'saturate(1.35) hue-rotate(0deg)'},
  Blue:{hex:'#2563eb',filter:'saturate(1.25) hue-rotate(205deg)'},
  Black:{hex:'#111827',filter:'grayscale(1) brightness(.38)'},
  White:{hex:'#f8fafc',filter:'grayscale(1) brightness(1.65)'},
  Green:{hex:'#16a34a',filter:'saturate(1.3) hue-rotate(70deg)'},
  Pink:{hex:'#ec4899',filter:'saturate(1.25) hue-rotate(315deg)'},
  Beige:{hex:'#d6b98c',filter:'sepia(.55) saturate(.75) brightness(1.08)'},
  Brown:{hex:'#7c3f20',filter:'sepia(.75) saturate(1.15) brightness(.9)'}
};
const SIZES = ['6','7','8','9','10'];
const KIDS_SIZES = ['11K','12K','13K','1','2','3'];

const PRODUCTS = [
 {id:'w-sandal',name:'Luna Strappy Sandals',category:'women',type:'sandals',price:1499,old:2199,rating:4.8,img:'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=900&q=85',colors:['Red','Black','Blue','Pink'],sizes:SIZES},
 {id:'w-sneaker',name:'Aero Street Sneakers',category:'women',type:'sneakers',price:2299,old:2999,rating:4.7,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',colors:['Red','Blue','White','Black'],sizes:SIZES},
 {id:'w-pump',name:'Classic Leather Pumps',category:'women',type:'shoes',price:2799,old:3499,rating:4.9,img:'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?auto=format&fit=crop&w=900&q=85',colors:['Black','Red','Beige','Pink'],sizes:SIZES},
 {id:'w-slip',name:'Everyday Slip-On',category:'women',type:'casual',price:1799,old:2399,rating:4.6,img:'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=85',colors:['White','Blue','Black','Pink'],sizes:SIZES},
 {id:'w-wedge',name:'Urban Comfort Wedges',category:'women',type:'shoes',price:2499,old:3299,rating:4.7,img:'https://images.unsplash.com/photo-1534653299134-96a171b61581?auto=format&fit=crop&w=900&q=85',colors:['Beige','Black','Red','White'],sizes:SIZES},
 {id:'w-trainer',name:'Flex Knit Trainers',category:'women',type:'sports',price:2399,old:3199,rating:4.8,img:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=85',colors:['Blue','Pink','White','Black'],sizes:SIZES},
 {id:'w-mule',name:'Minimal Chic Mules',category:'women',type:'casual',price:1999,old:2699,rating:4.6,img:'https://images.unsplash.com/photo-1581101767113-1677fc2beaa8?auto=format&fit=crop&w=900&q=85',colors:['Black','Brown','Beige','Red'],sizes:SIZES},
 {id:'w-high',name:'City High-Top Sneakers',category:'women',type:'sneakers',price:2599,old:3399,rating:4.8,img:'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=900&q=85',colors:['White','Blue','Pink','Black'],sizes:SIZES},

 {id:'m-runner',name:'Velocity Running Shoes',category:'men',type:'sports',price:2499,old:3299,rating:4.8,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',colors:['Red','Blue','Black','White'],sizes:SIZES},
 {id:'m-leather',name:'Executive Leather Loafers',category:'men',type:'formal',price:3199,old:4199,rating:4.9,img:'https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=900&q=85',colors:['Brown','Black','Beige'],sizes:SIZES},
 {id:'m-sneaker',name:'Urban Court Sneakers',category:'men',type:'sneakers',price:2199,old:2899,rating:4.7,img:'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=900&q=85',colors:['White','Blue','Black','Red'],sizes:SIZES},
 {id:'m-sandal',name:'Trail Comfort Sandals',category:'men',type:'sandals',price:1399,old:1999,rating:4.5,img:'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=85',colors:['Black','Brown','Blue'],sizes:SIZES},
 {id:'m-boot',name:'Rugged Trek Boots',category:'men',type:'shoes',price:3499,old:4599,rating:4.8,img:'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=900&q=85',colors:['Brown','Black','Beige'],sizes:SIZES},
 {id:'m-formal',name:'Oxford Office Classics',category:'men',type:'formal',price:3299,old:4299,rating:4.9,img:'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=900&q=85',colors:['Black','Brown','Beige'],sizes:SIZES},
 {id:'m-training',name:'Power Training Sneakers',category:'men',type:'sports',price:2699,old:3599,rating:4.7,img:'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=900&q=85',colors:['Blue','Red','Black','White'],sizes:SIZES},
 {id:'m-casual',name:'Weekend Canvas Sneakers',category:'men',type:'casual',price:1899,old:2499,rating:4.6,img:'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=85',colors:['White','Blue','Green','Black'],sizes:SIZES},

 {id:'k-sneaker',name:'Mini Star Sneakers',category:'kids',type:'sneakers',price:1199,old:1699,rating:4.8,img:'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=85',colors:['Blue','Red','Pink','White'],sizes:KIDS_SIZES},
 {id:'k-sandal',name:'Sunny Kids Sandals',category:'kids',type:'sandals',price:899,old:1299,rating:4.6,img:'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=900&q=85',colors:['Blue','Pink','Green','Red'],sizes:KIDS_SIZES},
 {id:'k-runner',name:'Junior Active Runners',category:'kids',type:'sports',price:1299,old:1799,rating:4.7,img:'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=85',colors:['Blue','Green','Red','Black'],sizes:KIDS_SIZES},
 {id:'k-slip',name:'Playtime Slip-Ons',category:'kids',type:'casual',price:999,old:1499,rating:4.5,img:'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=85',colors:['White','Blue','Pink','Green'],sizes:KIDS_SIZES},
 {id:'k-high',name:'Rainbow High-Tops',category:'kids',type:'sneakers',price:1399,old:1899,rating:4.8,img:'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=900&q=85',colors:['Red','Blue','Pink','Green'],sizes:KIDS_SIZES},
 {id:'k-light',name:'Light-Up Party Shoes',category:'kids',type:'shoes',price:1499,old:1999,rating:4.7,img:'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=900&q=85',colors:['Blue','Pink','White','Red'],sizes:KIDS_SIZES},
 {id:'k-school',name:'School Day Velcro Shoes',category:'kids',type:'shoes',price:1099,old:1599,rating:4.6,img:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85',colors:['Black','Blue','White'],sizes:KIDS_SIZES},
 {id:'k-sport',name:'Tiny Champion Trainers',category:'kids',type:'sports',price:1299,old:1799,rating:4.7,img:'https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=900&q=85',colors:['Red','Blue','Green','Black'],sizes:KIDS_SIZES}
];

const money = n => '₹' + Number(n).toLocaleString('en-IN');
const getCart = () => JSON.parse(localStorage.getItem('ffh_cart') || '[]');
const saveCart = c => {localStorage.setItem('ffh_cart',JSON.stringify(c)); updateCartCount();};
const getOrders = () => JSON.parse(localStorage.getItem('ffh_orders') || '[]');
const saveOrders = o => localStorage.setItem('ffh_orders',JSON.stringify(o));
const cartItems = () => getCart().map(x=>({...PRODUCTS.find(p=>p.id===x.id),qty:x.qty,size:x.size||'8',color:x.color||PRODUCTS.find(p=>p.id===x.id)?.colors?.[0]})).filter(Boolean);
const cartTotal = () => cartItems().reduce((s,p)=>s+p.price*p.qty,0);
function updateCartCount(){const n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll('.cart-count').forEach(e=>e.textContent=n);}
function getSelections(id){const size=document.getElementById(`size-${id}`)?.value || '8';const color=document.getElementById(`color-${id}`)?.value || PRODUCTS.find(p=>p.id===id)?.colors?.[0];return {size,color};}
function addToCart(id,size,color){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const sel={size:size||getSelections(id).size,color:color||getSelections(id).color};const c=getCart();const x=c.find(i=>i.id===id&&i.size===sel.size&&i.color===sel.color);if(x)x.qty++;else c.push({id,qty:1,...sel});saveCart(c);toast(`${p.name} · ${sel.color} · Size ${sel.size} added to cart`);}
function changeQty(id,d,size,color){const c=getCart(),x=c.find(i=>i.id===id&&(!size||i.size===size)&&(!color||i.color===color));if(!x)return;x.qty+=d;if(x.qty<=0)c.splice(c.indexOf(x),1);saveCart(c);renderCart();}
function toast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.style.cssText='position:fixed;right:20px;bottom:20px;background:#111827;color:#fff;padding:13px 18px;border-radius:12px;z-index:100;font-weight:800;max-width:360px';document.body.appendChild(t)}t.textContent=msg;t.style.display='block';clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.style.display='none',1800);}
function swatches(p,scope='card'){return `<div class="color-row"><span class="color-label">Color: <b id="selected-color-${scope}-${p.id}">${p.colors[0]}</b></span><div class="swatches">${p.colors.map((c,i)=>`<button type="button" class="swatch ${i===0?'selected':''}" title="${c}" aria-label="${c}" style="background:${COLORS[c].hex}" onclick="selectColor('${p.id}','${c}','${scope}',this)"></button>`).join('')}</div></div>`}
function sizeSelect(p){return `<label class="size-label">Size<select id="size-${p.id}">${p.sizes.map(s=>`<option>${s}</option>`).join('')}</select></label>`}
function productCard(p){return `<article class="product-card"><div class="product-visual" id="visual-${p.id}"><img id="img-${p.id}" class="product-img" src="${p.img}" alt="${p.name}" loading="lazy"></div><div class="product-body"><span class="badge">${p.category.toUpperCase()}</span><h3 class="product-title">${p.name}</h3><div class="rating">★★★★★ <span class="muted">${p.rating}</span></div><div><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span></div>${swatches(p)}${sizeSelect(p)}<div class="product-actions"><button class="btn btn-accent btn-sm" onclick="addToCart('${p.id}')">Add to Cart</button><a class="btn btn-light btn-sm" href="product.html?id=${p.id}">View</a></div></div></article>`}
function renderProducts(list,target='product-grid'){const el=document.getElementById(target);if(el)el.innerHTML=list.map(productCard).join('');}
function selectColor(id,color,scope,button){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const img=document.getElementById(scope==='detail'?`detail-img-${id}`:`img-${id}`);if(img)img.style.filter=COLORS[color]?.filter||'none';document.querySelectorAll(`.swatch`).forEach(b=>{if(b.closest('.product-card')||scope==='detail'){} });const parent=button?.closest('.color-row');if(parent){parent.querySelectorAll('.swatch').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');const label=parent.querySelector('.color-label b');if(label)label.textContent=color;}const hidden=document.getElementById(`selected-color-${scope}-${id}`);if(hidden)hidden.textContent=color;}
function setupCategory(cat){const grid=document.getElementById('product-grid'),search=document.getElementById('search'),sort=document.getElementById('sort'),type=document.getElementById('type');function go(){let a=PRODUCTS.filter(p=>p.category===cat);let q=(search?.value||'').toLowerCase();if(q)a=a.filter(p=>(p.name+p.type).toLowerCase().includes(q));if(type?.value)a=a.filter(p=>p.type===type.value);if(sort?.value==='low')a.sort((x,y)=>x.price-y.price);if(sort?.value==='high')a.sort((x,y)=>y.price-x.price);renderProducts(a);const count=document.getElementById('category-count');if(count)count.textContent=`${a.length} products`;}[search,sort,type].forEach(x=>x&&x.addEventListener('input',go));go();}
function renderCart(){const list=document.getElementById('cart-list'),summary=document.getElementById('cart-summary');if(!list)return;const items=cartItems();if(!items.length){list.innerHTML='<div class="empty"><h2>Your cart is empty</h2><p class="muted">Discover footwear made for every step.</p><a class="btn btn-accent" href="categories.html?cat=women">Shop Now</a></div>';if(summary)summary.innerHTML='';return;}list.innerHTML=items.map(p=>`<div class="cart-item"><img src="${p.img}" alt="${p.name}" style="filter:${COLORS[p.color]?.filter||'none'}"><div><b>${p.name}</b><div class="muted">${p.color} · Size ${p.size} · ${money(p.price)} each</div><div class="qty"><button onclick="changeQty('${p.id}',-1,'${p.size}','${p.color}')">−</button><b>${p.qty}</b><button onclick="changeQty('${p.id}',1,'${p.size}','${p.color}')">+</button></div></div><div><b>${money(p.price*p.qty)}</b><br><button class="btn btn-danger btn-sm" onclick="changeQty('${p.id}',-${p.qty},'${p.size}','${p.color}')">Remove</button></div></div>`).join('');const sub=cartTotal(),ship=sub>=999?0:79,tax=Math.round(sub*.05),total=sub+ship+tax;if(summary)summary.innerHTML=`<div class="summary-row"><span>Subtotal</span><b>${money(sub)}</b></div><div class="summary-row"><span>Shipping</span><b>${ship?money(ship):'FREE'}</b></div><div class="summary-row"><span>GST (5%)</span><b>${money(tax)}</b></div><div class="summary-row total"><span>Total</span><span>${money(total)}</span></div><a class="btn btn-accent" style="width:100%;margin-top:10px" href="delivery-address.html">Proceed to Checkout</a>`;}
function productDetail(){const id=new URLSearchParams(location.search).get('id'),p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0],el=document.getElementById('product-detail');if(!el)return;el.innerHTML=`<div class="checkout-grid"><div><div class="detail-visual"><img id="detail-img-${p.id}" class="hero-img" style="height:560px;filter:${COLORS[p.colors[0]]?.filter||'none'}" src="${p.img}" alt="${p.name}"></div></div><div class="panel" style="padding:35px"><span class="badge">${p.category}</span><h1 style="font-size:40px;line-height:1.05">${p.name}</h1><div class="rating">★★★★★ ${p.rating} · 128 reviews</div><p class="muted">Premium comfort and everyday style. Designed for confident steps with durable materials and a versatile silhouette.</p><div style="margin:25px 0"><span class="price" style="font-size:30px">${money(p.price)}</span> <span class="old-price">${money(p.old)}</span></div>${swatches(p,'detail')}<label class="size-label big">Select Size<select id="detail-size-${p.id}">${p.sizes.map(s=>`<option>${s}</option>`).join('')}</select></label><button class="btn btn-accent" style="width:100%;margin-top:15px" onclick="addToCart('${p.id}',document.getElementById('detail-size-${p.id}').value,document.querySelector('#product-detail .swatch.selected')?.title||'${p.colors[0]}')">Add to Cart</button><a class="btn btn-light" style="width:100%;margin-top:10px" href="review-rating.html?product=${p.id}">Read & Write Reviews</a><div class="feature-strip"><span>✓ Sizes ${p.sizes[0]}–${p.sizes[p.sizes.length-1]}</span><span>✓ ${p.colors.length} colors</span><span>✓ Easy 7-day returns</span></div></div></div>`;}
function setCheckoutSummary(){const el=document.getElementById('checkout-summary');if(!el)return;const sub=cartTotal(),ship=sub>=999?0:79,tax=Math.round(sub*.05),total=sub+ship+tax;el.innerHTML=`<h3>Order Summary</h3>${cartItems().map(p=>`<div class="summary-row"><span>${p.name} · ${p.color} · ${p.size} × ${p.qty}</span><b>${money(p.price*p.qty)}</b></div>`).join('')}<div class="summary-row"><span>Shipping</span><b>${ship?money(ship):'FREE'}</b></div><div class="summary-row"><span>GST</span><b>${money(tax)}</b></div><div class="summary-row total"><span>Total</span><span>${money(total)}</span></div>`;}
function bindCheckout(){setCheckoutSummary();const form=document.getElementById('checkout-form');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);localStorage.setItem('ffh_address',JSON.stringify(Object.fromEntries(fd.entries())));location.href='payment.html'});}
function bindPayment(){setCheckoutSummary();const form=document.getElementById('payment-form');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const order={id:'FFH'+Date.now().toString().slice(-8),date:new Date().toLocaleString('en-IN'),items:cartItems(),address:JSON.parse(localStorage.getItem('ffh_address')||'{}'),total:(()=>{let s=cartTotal();return s+(s>=999?0:79)+Math.round(s*.05)})(),status:'Confirmed',payment:form.elements.payment.value};const orders=getOrders();orders.unshift(order);saveOrders(orders);localStorage.setItem('ffh_last_order',order.id);localStorage.removeItem('ffh_cart');location.href='order-confirmation.html'});}
function renderOrderConfirmation(){const el=document.getElementById('confirmation');if(!el)return;const orders=getOrders(),id=localStorage.getItem('ffh_last_order'),o=orders.find(x=>x.id===id)||orders[0];if(!o){el.innerHTML='<div class="empty"><h2>No recent order found.</h2><a class="btn btn-accent" href="index.html">Go Home</a></div>';return}el.innerHTML=`<div class="panel" style="padding:45px;text-align:center"><div style="font-size:55px">✓</div><h1>Order Confirmed</h1><p class="muted">Thank you for shopping with REDTAPE Footwear Hub.</p><div class="notice">Order ID: ${o.id}</div><a class="btn btn-accent" href="tracking.html?id=${o.id}">Track Order</a> <a class="btn btn-light" href="orders.html">My Orders</a></div>`;}
function renderOrders(){const el=document.getElementById('orders-list');if(!el)return;const os=getOrders();if(!os.length){el.innerHTML='<div class="empty"><h2>No orders yet</h2><a class="btn btn-accent" href="categories.html?cat=women">Start Shopping</a></div>';return}el.innerHTML=os.map(o=>`<div class="panel order-card"><div style="display:flex;justify-content:space-between;gap:15px;flex-wrap:wrap"><div><b>${o.id}</b><div class="muted">${o.date}</div></div><span class="badge">${o.status}</span></div><div class="summary-row"><span>${o.items.map(i=>`${i.name} (${i.color}, ${i.size}) × ${i.qty}`).join(', ')}</span><b>${money(o.total)}</b></div><a class="btn btn-light btn-sm" href="tracking.html?id=${o.id}">Track</a></div>`).join('');}
function renderTracking(){const el=document.getElementById('tracking');if(!el)return;const id=new URLSearchParams(location.search).get('id')||localStorage.getItem('ffh_last_order'),o=getOrders().find(x=>x.id===id)||getOrders()[0];if(!o){el.innerHTML='<div class="empty"><h2>No order found</h2></div>';return}el.innerHTML=`<div class="panel" style="padding:30px"><h2>Track ${o.id}</h2><div class="status"><div class="status-step done"><div class="status-dot">✓</div>Confirmed</div><div class="status-step done"><div class="status-dot">✓</div>Packed</div><div class="status-step current"><div class="status-dot">3</div>Shipped</div><div class="status-step"><div class="status-dot">4</div>Out for delivery</div><div class="status-step"><div class="status-dot">5</div>Delivered</div></div><p class="muted">Your order is moving through our delivery network.</p></div>`;}
function bindReview(){const stars=document.querySelectorAll('#stars button'),form=document.getElementById('review-form'),out=document.getElementById('reviews');let rating=5;stars.forEach((b,i)=>b.addEventListener('click',()=>{rating=i+1;stars.forEach((x,j)=>x.classList.toggle('on',j<i+1))}));stars.forEach(b=>b.classList.add('on'));if(form)form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const key='ffh_reviews';const rs=JSON.parse(localStorage.getItem(key)||'[]');rs.unshift({name:fd.get('name'),rating,text:fd.get('text'),date:new Date().toLocaleDateString('en-IN')});localStorage.setItem(key,JSON.stringify(rs));form.reset();toast('Review submitted');showReviews()});function showReviews(){if(out){const rs=JSON.parse(localStorage.getItem('ffh_reviews')||'[]');out.innerHTML=rs.length?rs.slice(0,6).map(r=>`<div class="review"><b>${r.name}</b> <span class="rating">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</span><div class="muted">${r.date}</div><p>${r.text}</p></div>`).join(''):'<p class="muted">Be the first to review.</p>'}}showReviews();}
function bindContact(){const f=document.getElementById('contact-form');if(f)f.addEventListener('submit',e=>{e.preventDefault();f.reset();document.getElementById('contact-msg').textContent='Thanks! Your message has been received. Our team will contact you shortly.'});}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();renderCart();productDetail();setupCategory(document.body.dataset.category);bindCheckout();bindPayment();renderOrderConfirmation();renderOrders();renderTracking();bindReview();bindContact();});
